import bgImage from './src/assets/backgroundImg.png'
import MainLogo from './src/assets/Logo.png'
import settingIcon from './src/assets/SettingIcon.png'
import linkIcon from './src/assets/linkIcon.png'
import analiticIcon from './src/assets/analyticIcon.png'
import dashboardIcon from './src/assets/dashboardIcon.png'
import actvitelinkIcon from './src/assets/activeLinkIcon.png'
import activesettingIcon from './src/assets/activeSettingIcon.png'
import activeanaliticIcon from './src/assets/activeAnalyticsIcon.png'
import activedashboardIcon from './src/assets/activeDashboardIcon.png'
import searchIccon from './src/assets/searchIcon.png'
import EditIcon from './src/assets/EditIcon.png'
import DeleteIcon from './src/assets/DeleteIcon.png'
import CopyIcon from './src/assets/CopyIcon.png'
import AscendingSortIcon from './src/assets/Assend.png'
import DescendingSortIcon from './src/assets/Desend.png'
import NextIcon from './src/assets/nextIcon.png'
import PreviousIcon from './src/assets/previousIcon.png'
import CopiedIcon from './src/assets/copiedlink.png'

export  {CopiedIcon,NextIcon,PreviousIcon,AscendingSortIcon,DescendingSortIcon,EditIcon,DeleteIcon,CopyIcon,searchIccon,bgImage,MainLogo,settingIcon,linkIcon,analiticIcon,dashboardIcon,activeanaliticIcon,activedashboardIcon,activesettingIcon,actvitelinkIcon};